.github/pull_request_template.md

minor updates pull_request_template
Chore
Probar pull_request_template
Probar si funciona
- Cambio un caracter para probar funcionamiento
- [❎] Test performed
@AntonioMrtz

chore : minor updates pull_request_template

---

Electron/src/renderer/App.tsx
Electron/src/renderer/AppCss.module.css

Elimininado conflicto entre scrollBar de la seccion mainContentWrapper y la scrollBar de la propia aplicación de escritorio.
Fix
Cuando se scrolleaba en el mainContentWrapper el contenido no se llegaba a mostrar en pantalla debido a que la scrollBar exterior de la aplicación no se movía.
* Eliminar el height : 99svh del mainContentWrapper para eliminar el conflicto entre los scrollbar
* Añadir min-height : 99svh al mainContentWrapper para que las secciones que no ocupaban la pantalla entera siguieran rellenando el contenedor principal de la aplicación.
- mainContentWrapper Heigth:99svh -> eliminado 
- mainContentWrapper min-heigth:99svh 
- [] Test performed 
@AntonioMrtz

Conflict scroll bar main content wrapper with app scroll bar

---

Electron/src/componentes/InfoPopover/InfoPopover.tsx
Electron/src/componentes/Playlist/Song/ContextMenuSong/ContextMenuSong.tsx
Electron/src/componentes/Playlist/Song/ContextMenuSong/contextMenuSong.module.css
Electron/src/componentes/Sidebar/ModalAddSongPlaylist/Accordion/AddSongPlayListAccordion.tsx
Electron/src/componentes/types/InfoPopover.ts

Reestructurado el componente InfoPopover para poder ser utilizado desde los demás componentes.
Ahora contiene:
* Title : informacion principal que se mostrará en el Popover
* Description : información secundaria que se mostrará Popover
* HandleClose : si se necesitará ejecutar algún método del padre al cerrar el PopOver
* triggerOpenConfirmationModal : valor boolean que al cambiar fuerza un refresco en el componente InfoPopover
Refactor
El componente ConfirmationMenu era demasiado monolítico/inflexible e iba a ser usado en más sitios de la aplicación.
Refactorizar los campos como props para poder establecer Boton , texto primario y descripcion.
- Refactorización InfoPopover
- Adaptación componentes que lo usaban anteriormente
Comportamiento inesperado en los componentes que lo usaban …

refactor : InfoPopover refactorizado 

---

Backend API/main.py
Backend API/services/playlist_service.py
Electron/src/componentes/InfoPopover/InfoPopover.tsx
Electron/src/componentes/Playlist/Playlist.tsx
Electron/src/componentes/Sidebar/Playlist/ContextMenuSong/ContextMenuPlaylist.tsx
Electron/src/componentes/Sidebar/Playlist/ContextMenuSong/contextMenuPlaylist.module.css
Electron/src/componentes/Sidebar/Playlist/Playlist.tsx
Electron/src/componentes/Sidebar/Sidebar.tsx
Electron/src/componentes/Sidebar/types/propsPlaylist.module.ts

Context Menu para las playlist que aparecen en el sidebar. Se ha implementado la funcion de compartir,eliminar playlist y añadir canciones de una playlist a otra.
Feat
- InfoPopover de mensajes de confirmacion refactorizado usando usereducer 
- Metodos eliminar playlist y añadir canciones de una playlist a otra
- Backend método Eliminar Playlist
* Actualización del sidebar
* Nuevo metodo en API Eliminar Playlist
@AntonioMrtz

feat : Context Menu Playlist Sidebar

---

Backend API/main.py
Electron/src/componentes/Playlist/Playlist.tsx

No documentado 
- Clase main documentada con lo referente a la descripcion 
-Documentacion de la clase main
- Change 2
- Change 3
@AntonioMrtz

Fix:description 

---

Electron/src/componentes/Playlist/Playlist.tsx
Electron/src/componentes/Playlist/playlist.module.css

Añadir valor onClick y cambio de estilo a los botones de las playlist 
- Las Playlist ahora cuentan con botones funcionales para el play y el me gusta 
- Inciso aun no tiene función de iniciar el sonido de la lista 
- Botones de corazón
- Botones de Play
- Estados de Me gusta de la playlist y sonando
Problemas cuando tengamos que llamar a la cola de la playlist y hacer sonar todas las canciones contenidas en ella  
@AntonioMrtz

Feat:Subheader playlist

---

.github/workflows/main.yml

- Change 1
- Change 2
- Change 3
- [] Test performed 
@AntonioMrtz

fix : obtener env desde Repo Git y pasarlo a los tests

---

Electron/src/componentes/Playlist/Playlist.tsx

El contextMenu para Playlist se despliega al clickar el icono ellipsis en la pantalla Playlist
Feat
- Añadido ContextMenu Playlist
- Renombrado Modal Update Playlist para evitar conflictos
@AntonioMrtz

feat : Playlist > Subheader > Ellipsis > ContextMenu DONE

---

Electron/src/componentes/Playlist/Playlist.tsx

Mejora rendimiento obtener canciones para cada Playlist y arreglar lint en dicho segmento.
Fix
Problemas de rendimiento y lint en el bucle que con los nombres de las canciones obtenia los datos de estas.
Uso de promesas y forEach no bloqueante para mejorar rendimiento y tener un Lint correcto.
- Cambio bucle for of por foeach con promesas
- Lint arreglado
@AntonioMrtz

fix : lint fix Playlist > FetchSongData + improved performance

---

Electron/src/componentes/Home/Playlist/Playlist.tsx

Añadido ContextMenu a las Playlist de la sección Home.
Feat
- Añadido Componente ContextMenuPlaylist a Home>Playlist
- Actualizado imports y añadido funcionalidad para el funcionamiento del ContextMenu
@AntonioMrtz

feat : add ContextMenuPlaylist to Home > Playlist

---

Electron/src/componentes/Home/Home.tsx

Añadir círculo de carga mientras las playlists en Menu Home no han sido cargadas.
Feat
- Añadido LoadingCircle y adaptado al código
@AntonioMrtz

feat : add loading circle while playlist not fetched

---

Electron/src/componentes/ContextMenu/Playlist/ContextMenuPlaylist.tsx
Electron/src/componentes/ContextMenu/Song/ContextMenuSong.tsx

Ajustar posicionamiento LoadingCircle en el ContextMenu
Fix
- Ajustar posicionamiento LoadingCircle en el ContextMenu
@AntonioMrtz

fix : show loadingcircle in the center ContextMenu

---

Backend API/src/__tests__/test_all_users.py
Backend API/src/__tests__/test_dto.py
Backend API/src/__tests__/test_song.py
Backend API/src/services/all_users_service.py
Backend API/src/services/artist_service.py
Backend API/src/services/playlist_service.py
Backend API/src/services/song_service.py

Añadir o borrar canción de las canciones subidas por artista en caso de que se borre o añada una canción.
Feat
- Crear y borrar canción elimina o añade canciones en uploaded_songs del artista
- Tests correspondientes
@AntonioMrtz

feat : create/delete song with uploaded_songs artist and tests

---

Backend API/src/services/all_users_service.py
Backend API/src/services/artist_service.py
Backend API/src/services/dto_service.py
Backend API/src/services/playlist_service.py
Backend API/src/services/song_service.py
Backend API/src/services/user_service.py

Base de datos personalizada para ejecutar los tests y no influir con la base de datos de producción
Test
- Añadir condición de pytest entre los modulos para usar colecciones de test o normales
@AntonioMrtz

test : add test.* collection for testing

---

Electron/src/componentes/AdvancedUIComponents/ContextMenu/Song/ContextMenuSong.tsx
Electron/src/componentes/Genre/Genre.tsx
Electron/src/componentes/Profile/UserProfile/UserProfile.tsx
Electron/src/componentes/SongCard/SongCard.tsx
Electron/src/renderer/App.tsx

ContextMenu para canciones estando fuera de una playlist.
Feat
- Aplicada Composition al componente ContextMenuSong para que si no está en playlist no muestre funcionalidades relacionadas con su playlist.
- Adaptación para el componente SongCard
@AntonioMrtz

feat : add Composition to ContextMenuSong(No playlist)

---

Electron/src/componentes/AdvancedUIComponents/ContextMenu/Playlist/ContextMenuPlaylist.tsx
Electron/src/componentes/AdvancedUIComponents/ContextMenu/types/PropsContextMenu.tsx
Electron/src/componentes/Playlist/Playlist.tsx
Electron/src/componentes/PlaylistCard/PlaylistCard.tsx
Electron/src/componentes/Sidebar/Playlist/Playlist.tsx
Electron/src/componentes/Sidebar/Sidebar.tsx
Electron/src/componentes/Sidebar/types/propsPlaylist.module.ts

Botón eliminar se muestra desactivado en caso de que el usuario no sea el propietario de la Playlist,
Feat
- ContextMenuPlaylist añadir comprobación si es usuario
- Añadir owner como prop en PropsContextMenuPlaylist y Sidebar -> Playlist
- Adaptar llamadas con nuevos props
@AntonioMrtz

feat : add disabled button and style if not owner

---

Electron/src/componentes/Sidebar/ModalAddSongPlaylist/Accordion/AddSongPlayListAccordion.tsx

Añadida comprobación para que solo los artistas puedan crear canciones.
Feat
- Añadir comprobación si es artista en interfaz
@AntonioMrtz

feat : song create only available if user

---

Electron/src/componentes/Playlist/Playlist.tsx

Sidebar solo carga las canciones del usuario guardadas y las creadas por él.
Feat
- Cambiar petición de todas las playlist a solo las creadas y guardadas por el usuario.
@AntonioMrtz

feat : sidebar only displays saved playlist and playlist of user

---

Electron/src/componentes/AdvancedUIComponents/ContextMenu/Song/ContextMenuSong.tsx

Solo se permite añadir canciones a una playlist al creador de ésta.
Feat
- Modificar peticion a backend con solo las playlist del usuario.
@AntonioMrtz

feat : add songs to playlist only owner

---

Electron/src/componentes/Playlist/Playlist.tsx
Electron/src/componentes/Playlist/Song/Song.tsx
Electron/src/componentes/Playlist/playlist.module.css
Electron/src/componentes/Sidebar/types/propsSongs.module.ts

Añadido campo número de reproducciones para las canciones en una Playlist.
Feat
- Añadir campo número reproducciones a Playlist > Song
@AntonioMrtz

feat : add play count to Playlist > Song

---

Electron/src/componentes/Sidebar/ModalAddSongPlaylist/Accordion/AddSongPlayListAccordion.tsx
Electron/src/componentes/Sidebar/ModalAddSongPlaylist/ModalAddSongPlaylist.tsx

Deshabilitar la capacidad del usuario de cerrar el modal cuando se esté creando una canción o playlist
Feat
- Modificar AddSongPlaylistAccordion para ofrecer la opción de cerrar o no dependiendo de un estado
@AntonioMrtz

Feat/upload song & playlist disable close while uploading

---

Electron/src/componentes/AdvancedUIComponents/ContextMenu/Profile/ContextMenuProfile.tsx
Electron/src/componentes/StickyHeader/StickyHeader.tsx
Electron/src/renderer/App.tsx

ContextMenu al clickar en Sticky Profile que incluye Perfil y Cerrar Sesión.
Feat
- Añadido ContextMenuProfile
- Código adaptación StickyProfile para desplegar el PopOver
@AntonioMrtz

feat : add Logout ContextMenu

---

.github/workflows/generate-docs.yml
Backend API/src/generate-docs.py

Generación de html con documentación de la API mediante githubactions
- Creado archivo workflow para generar documentación API
- Script generación documentación
@AntonioMrtz

Feat/generate docs GitHub actions

---

.github/workflows/generate-docs.yml

- Change 1
- Change 2
- Change 3
- [] Test performed 
@AntonioMrtz

feat : use pat

---

.github/workflows/generate-docs.yml

- Change 1
- Change 2
- Change 3
- [] Test performed 
@AntonioMrtz

fix : credentials

---

Backend API/.vscode/extensions.json
Electron/.vscode/extensions.json

Add recommended VSCODE extensions
Chore
- Add recommended VSCODE extensions
@AntonioMrtz

chore : add recommended extensions

---

Backend/src/main.py
Backend/src/middleware/middleware.py
Backend/src/model/Playlist.py
Backend/src/routers/artistas.py
Backend/src/routers/canciones.py
Backend/src/routers/playlists.py
Backend/src/routers/usuarios.py
Backend/src/services/all_users_service.py
Backend/src/services/artist_service.py
Backend/src/services/dto_service.py
Backend/src/services/playlist_service.py
Backend/src/services/security_service.py
Backend/src/services/song_service.py
Backend/src/services/user_service.py
Backend/tests/test_all_users.py
Backend/tests/test_artist.py
Backend/tests/test_dto.py
Backend/tests/test_user.py
docs/backend/SETUP.md

Solve circular imports and asociated duplicated code
Refactor
- Change imports for import x as x_service
- Delete database collection access from multiple service modules
- Delete duplicated methods asociated with circular imports
@AntonioMrtz

refactor : solve circular imports and asociated duplicated code

---

.github/CONTRIBUTING.md
.github/workflows/backend-black.yml
.github/workflows/backend-tests.yml
.github/workflows/generate-docs.yml
Backend/Dockerfile
docs/secondary_architectures/db-blob/Dockerfile

Migrate towards Python 3.11
Chore
- Update docs CONTRIBUTING
- Update Dockerfiles
- Update Github Actions yml
@AntonioMrtz

chore : migrate to python 3.11

---

Backend/app/boostrap/PropertiesManager.py

Add load config var for properties manager
Feat
- Modify PropertiesManager for reading config.ini app configs
@AntonioMrtz

feat : add load config var for properties manager

---

Backend/install-all-requirements.sh

Add script to install all requirements for Backend
Chore
- Add mentioned script
@AntonioMrtz

Add script to install all requirements for Backend

---

Backend/requirements.txt

Delete unused botocore3 dependency
Chore
- Remove botocore3 dependency from requirements
@AntonioMrtz

Delete botocore3 dependency

---

docs/backend/Docker.md
docs/backend/Enviroment.md
docs/backend/Testing.md

Updates testing docs with enviroment info needed for executing tests with different architectures.
Docs
- Not enough information about enviroments during testing.
- Provide information about enviroments during testing.
- Add information about enviroments during backend testing
N/A
@AntonioMrtz

Update backend testing enviroment variables behaviour

---

Backend/app/tools/generate_mock_data.py
Backend/app/tools/generate_openapi.py
Backend/tests/test_API/api_test_playlist.py
Backend/tests/test_API/api_token.py
Backend/tests/test__artist.py
Backend/tests/test__base_users.py
Backend/tests/test__genre.py
Backend/tests/test__login.py
Backend/tests/test__playlist.py
Backend/tests/test__search.py
Backend/tests/test__song.py
Backend/tests/test__user.py
docs/utils/Generate-Mock-Data.md
docs/utils/Generate-OpenAPI.md
mkdocs.yml

Create a tool for generating small/medium/large amout of mock data for the app
Feat
- Create the script
- Update the docs
@AntonioMrtz

Generate Mock Data Tool

---

.github/workflows/generate-openapi.yml

Make generate-openapi pipeline successful even if `openapi.json` is up to date
ci
- Make generate-openapi pipeline successful even if `openapi.json` is up to date
@AntonioMrtz

Make generate-openapi pipeline successful even if `openapi.json` is up to date

---

.devcontainer/Backend/devcontainer.json

Add Backend Dev containers configuration
Build
- Add config for backend dev containers
@AntonioMrtz

Add Backend Dev containers

---

Backend/app/__main__.py
docs/backend/Testing.md

Improve Backend OpenAPI metadata like email, license etc.
Chore
- Add `license_info` and `contact` fields on Backend API metadata
@AntonioMrtz

Improve Backend OpenAPI metadata

---

Electron/src/main/main.ts
docs/Auth-Login.md
docs/backend/Auth-Login.md
docs/backend/FAQ.md
docs/backend/File-Structure.md
docs/backend/SETUP.md
docs/backend/Testing.md
docs/frontend/FAQ.md
docs/frontend/File-Structure.md
mkdocs.yml

Add FAQ docs
docs
- Add FAQ to docs
@AntonioMrtz

docs: add FAQ for frontend and backend

---

Backend/docker/docker-compose-base.yml
Backend/docker/docker-compose-dev.yml

Modify docker compose for backend container depending on mongodb one while dev mode.
Build
- Add healthchecks for containers
- Backend container dependency on mongodb while dev mode
- Dev and prod deployments
@AntonioMrtz

Backend container depends on MongoDB container for development

---

.pre-commit-config.yaml
docs/Git-Convention.md
docs/SETUP.md

Add Git/Github Issue Traceability
feat
- Add pre-commit for autogenerate commit message with issue number
- Create convention for PR, branches and commits
- Update docs
@AntonioMrtz

#182: Issue Traceability

---

.github/CODEOWNERS

Add default reviewers for PRs
chore
- Add default reviewers for PRs
@AntonioMrtz

#184:  Default reviewers

---

Electron/src/main/main.ts
Electron/src/main/util.ts

Remove interceptor headers electron as is no longer needed
Feat
- Remove interceptor call on window
- Move interceptor to utils
@AntonioMrtz

#194: Frontend onBeforeSendHeaders / include credentials

---

docs/utils/Mkdocs.md
mkdocs.yml

Add Mkdocs docs for development and deployment
Docs
- Add Mkdocs docs
@AntonioMrtz

#200: Mkdocs docs

---

.github/disabled_workflows/backend-black.yml
.github/disabled_workflows/enforce-branch-name.yml
.github/workflows/backend-build.yml
.github/workflows/backend-tests-database-blob.yml
.github/workflows/backend-tests-streaming-serverless.yml
.github/workflows/openapi-schema-client.yml
Backend/app/common/PropertiesManager.py
Backend/docker/build_and_up_dev.sh
Backend/docker/build_and_up_prod.sh
Backend/docker/docker-compose-base.yml

Build backend pipeline on PR commits
Build
#216
- Add backend build pipeline on PR commit
- Fix backend not loading all environments if one was missing
- Replace `docker-compose` with `docker compose` for build scripts
@AntonioMrtz

#216: Backend Build Pipeline

---

Electron/.vscode/launch.json
docs/backend/Environment.md
docs/backend/SETUP.md
docs/backend/Testing.md
docs/frontend/SETUP.md
docs/frontend/Testing.md
docs/utils/Release-Procedure.md
docs/utils/Testing-Principles.md
mkdocs.yml

Enable Frontend debug Electron + React and document it
Feat
#237
- Enable frontend debug
- Refactor docs for debug run
@AntonioMrtz

#237: Frontend debug Electron + React

---

Backend/app/spotify_electron/stream/stream_controller.py
Backend/app/spotify_electron/user/user_controller.py

Enable missing auth on new endpoints
Fix
#242 
- Enable auth via token JWT on missing endpoints
@AntonioMrtz

#242:Enable missing auth on new endpoints

---

.github/workflows/backend-build.yml
Backend/docker/build_and_up_dev.sh
Backend/docker/build_and_up_dev_backend.sh
Backend/docker/build_and_up_dev_standalone.sh
Backend/docker/docker-compose-dev-backend.yml
Backend/docker/docker-compose-dev-standalone.yml
Backend/docker/docker-compose-prod.yml
Backend/docker/env/prod.env
README.md
docs/backend/Docker.md
docs/backend/Environment.md
docs/backend/FAQ.md
docs/backend/File-Structure.md
docs/backend/SETUP.md
docs/backend/Testing.md
docs/frontend/SETUP.md
docs/utils/Mkdocs.md

* Add frontend development docker compose and script. 
* Dev Backend docker compose/script now only ships dependencies instead of the app. 
* Prod Backend now ships MongoDB database with new environments for it
* Docs update
Build
#251
- Add frontend dev docker
- Update backend dev docker
- Update backend prod docker
- Update docs for set up and environments
@AntonioMrtz

#251: Docker script for Frontend dev and update set ups

---

Electron/package.json

Standarize app package naming to follow naming convention SpotifyElectron-{version}.{outputformat}
Build
#256
- Standarize packaged app output name
@AntonioMrtz

#256: Standarize app package naming

---

.github/disabled_workflows/backend-tests-streaming-serverless.yml
.github/disabled_workflows/generate-docs.yml
.github/disabled_workflows/generate-openapi-schema-client.yml
.github/workflows/backend-tests-database-blob.yml
.github/workflows/openapi-check-updated.yml
Backend/Dockerfile
Backend/app/__main__.py
Backend/app/auth/auth_schema.py
Backend/app/auth/auth_service.py
Backend/app/common/PropertiesManager.py
Backend/app/common/app_schema.py
Backend/app/spotify_electron/song/providers/song_collection_provider.py
Backend/app/spotify_electron/song/providers/song_service_provider.py
Backend/app/spotify_electron/song/song_service_constants.py
Backend/docker/env/dev.env
Backend/docker/env/prod.env
Backend/tests/test__properties_manager.py
Electron/src/components/AdvancedUIComponents/ContextMenu/Playlist/ContextMenuPlaylist.tsx
docs/developer/backend/Environment.md

Make SECRET_SIGN_KEY environment auto-generated on backend start
Refactor
#277 
- Generate `SECRET_SIGN_KEY` on app start up
- Delete `SECRET_SIGN_KEY` env value
- Update docs 
@AntonioMrtz

#277: Make SECRET_SIGN_KEY environment auto-generated on backend start

---

docs/CONTRIBUTING.md

Improve required tools documentation
Docs
#279 
- Add download/installation guides link
@AntonioMrtz

#279: Improve required tools documentation

---

.github/disabled_workflows/generate-openapi-schema-client.yml
.github/workflows/openapi-check-updated.yml
.github/workflows/ruff-format-check.yml
.github/workflows/ruff-lint-check.yml
Backend/app/spotify_electron/song/serverless/song_serverless_api.py
Backend/app/spotify_electron/stream/stream_service.py
Backend/app/spotify_electron/user/base_user_service.py
Backend/requirements-dev.txt
Backend/tests/test__stream.py

Migrate to official ruff format lint action
Feat
#304 
- Use official Ruff astral actions
- Run format/lint on codebase
- Fix ruff version on pipelines
@AntonioMrtz

#304: Migrate to official ruff format lint action

---

.devcontainer/Backend/devcontainer.json
.github/disabled_workflows/backend-black.yml
.github/disabled_workflows/backend-tests-streaming-serverless.yml
.github/disabled_workflows/generate-docs.yml
.github/disabled_workflows/generate-openapi-schema-client.yml
.github/workflows/backend-tests-database-blob.yml
.github/workflows/openapi-check-updated.yml
Backend/Dockerfile
Backend/ruff.toml
docs/CONTRIBUTING.md
docs/developer/backend/SETUP.md
docs/developer/utils/Mkdocs.md

Migration to python 3.12
Feat
#308 
*  Bum python version
* Update docs
* Update actions
@AntonioMrtz

#308: Python3.12 migration

---

Backend/requirements-test.txt
Backend/requirements.txt

Bump backend dependencies:
* python-multipart to 0.0.20
* Bump fastapi to 0.115.7
* Bump uvicorn to 0.34
* Bump mongomock to 4.12
* Bump pymongo to 4.10
Chore
#310 
* python-multipart to 0.0.20
* Bump fastapi to 0.115.7
* Bump uvicorn to 0.34
* Bump mongomock to 4.12
* Bump pymongo to 4.10
@AntonioMrtz

#310: Bump backend dependencies

---

Backend/app/spotify_electron/user/artist/artist_controller.py
Backend/app/spotify_electron/user/artist/artist_repository.py
Backend/app/spotify_electron/user/artist/artist_schema.py
Backend/app/spotify_electron/user/artist/artist_service.py
Backend/app/spotify_electron/user/base_user_controller.py
Backend/app/spotify_electron/user/base_user_schema.py
Backend/app/spotify_electron/user/base_user_service.py
Backend/app/spotify_electron/user/user/user_repository.py
Backend/app/spotify_electron/user/user/user_schema.py
Backend/app/spotify_electron/user/user/user_service.py
Backend/tests/test__artist.py
Backend/tests/test__base_users.py
Backend/tests/test__user.py

Improve users exception handling. Fixes of #159 
Feat
#313 
-  Improve users exception handling
- Full test coverage for user entities
* Error handling inside the users entities. Code 500 because of unhandled exception types
@AntonioMrtz

#313: Improve users exception handling

---

Backend/app/auth/JWTBearer.py
Backend/app/spotify_electron/stream/stream_service.py
Backend/app/spotify_electron/utils/audio_management/audio_management_utils.py
Backend/app/spotify_electron/utils/json_converter/json_converter_utils.py
Backend/ruff.toml

Force chain exceptions with B904 ruff rule. Raising exceptions without chaining them to previous ones was not being detected statically
Feat
#315 
- Add ruff rule
- Fix B904 lint errors
@AntonioMrtz

#315: Force chain exceptions with B904 ruff rule

---

.pre-commit-config.yaml
Backend/app/auth/JWTBearer.py
Backend/app/auth/auth_service.py
Backend/app/auth/auth_service_validations.py
Backend/app/spotify_electron/genre/genre_schema.py
Backend/app/spotify_electron/genre/genre_service.py
Backend/app/spotify_electron/playlist/playlist_controller.py
Backend/app/spotify_electron/playlist/playlist_repository.py
Backend/app/spotify_electron/playlist/playlist_service.py
Backend/app/spotify_electron/playlist/validations/playlist_repository_validations.py
Backend/app/spotify_electron/playlist/validations/playlist_service_validations.py
Backend/app/spotify_electron/search/search_service.py
Backend/app/spotify_electron/song/base_song_repository.py
Backend/app/spotify_electron/song/base_song_schema.py
Backend/app/spotify_electron/song/blob/song_repository.py
Backend/app/spotify_electron/song/blob/song_service.py
Backend/app/spotify_electron/song/blob/validations/song_repository_validations.py
Backend/app/spotify_electron/song/serverless/song_service.py
Backend/app/spotify_electron/song/song_controller.py
Backend/app/spotify_electron/user/artist/artist_repository.py
Backend/app/spotify_electron/user/base_user_service.py
Backend/requirements-dev.txt
Backend/ruff.toml
Backend/tests/test__genre.py
requirements-global.txt

Force up-to-date raised exceptions on docstrings. Rule [DOC501](https://docs.astral.sh/ruff/rules/docstring-missing-exception/)
Feat
#318 
- Add ruff rule DOC501
- Fix other preview rules being enabled
- Fix ruff rule DOC501 issues detected on code
@AntonioMrtz

#318: Force up-to-date raised exceptions on docstrings

---

Backend/app/spotify_electron/playlist/playlist_controller.py
Backend/ruff.toml

Add FastAPI (FAST) ruff rules. [Rules](https://docs.astral.sh/ruff/rules/#fastapi-fast)
Feat
#317 
- Add ruff rule FAST
- Solve linting issues related to FAST
@AntonioMrtz

#317: Add FastAPI (FAST) ruff rules

---

Backend/app/__main__.py
Backend/app/common/PropertiesManager.py
Backend/app/common/app_schema.py
Backend/app/logging/LogPropertiesManager.py
Backend/app/logging/logging_schema.py
Backend/app/spotify_electron/song/providers/song_collection_provider.py
Backend/tests/test__properties_manager.py

Test environment with multiple workers produce unexpected database behaviour. Request to different workers will have different database data.
Fix
#321 
- Only enable selectable number of workers if production
- Replace `__getattr__` and `__settattr__` where needing for public `gettattr()` and `setattr()` public methods
@AntonioMrtz

#321: Test environment with multiple workers produce unexpected database behaviour

---

Backend/app/auth/auth_service.py
Backend/app/spotify_electron/playlist/playlist_service.py
Backend/app/spotify_electron/song/serverless/song_service.py
Backend/app/spotify_electron/utils/json_converter/json_converter_utils.py
Backend/ruff.toml

Force docstrings only on directly raised exceptions with DOC502 ruff rule. [Rule](https://docs.astral.sh/ruff/rules/docstring-extraneous-exception/)
Feat
#325 
- Add DOC502 rule
- Fix associated problems with the rule
@AntonioMrtz

#325: Force docstrings only on directly raised exceptions with DOC502 ruff rule

---

Backend/app/auth/JWTBearer.py
Backend/app/spotify_electron/genre/genre_controller.py
Backend/app/spotify_electron/playlist/playlist_controller.py
Backend/app/spotify_electron/search/search_controller.py
Backend/app/spotify_electron/song/song_controller.py
Backend/app/spotify_electron/stream/stream_controller.py
Backend/app/spotify_electron/user/artist/artist_controller.py
Backend/app/spotify_electron/user/base_user_controller.py

Replace the declaration of JWTBearer on every endpoint with a type alias
Refactor
#335 
- Replace dependency injection declaration of every endpoint with a common type alias for `Token = Annotated[TokenData, Depends(JWTBearer())]
`
@AntonioMrtz

#335: JWTBearer dependency replace with type alias

---

mkdocs.yml

This adds the licence's  in the MkDocs
`docs`: changes to the documentation.
#297 
- Adding copyright 
@AntonioMrtz

#297: Add licence to MkDocs

---

Backend/app/__main__.py
Backend/app/database/DatabaseConnectionManager.py
Backend/app/database/database_schema.py
Backend/app/spotify_electron/song/providers/song_collection_provider.py

Close MongoDB connection on shutdown
Feat
#349 
- Close client on app shutdown
- Fix private attributes being accessed  directly by other classes
- If closed connection is accessed it will get re-opened. From motor version `>=4.0` this behaviour is removed.
@AntonioMrtz

#349: Close MongoDB connection on shutdown

---

.github/workflows/backend-build.yml
.github/workflows/backend-image-push.yml
.github/workflows/backend-tests-database-blob.yml
.github/workflows/backend-type-checking.yml
.github/workflows/deploy-gh-pages-website.yml
.github/workflows/eslint-check.yml
.github/workflows/frontend-style-prettier.yml
.github/workflows/frontend-tests.yml
.github/workflows/openapi-check-updated.yml
.github/workflows/ruff-format-check.yml
.github/workflows/ruff-lint-check.yml

Set the minimum required permissions in every workflow
CI
#386 
- Set the minimum required permissions in every workflow
@AntonioMrtz

#386: Workflow does not contain permissions
